FROM node:lts-alpine

WORKDIR /app

COPY package.json /app/package.json

COPY . /app

COPY prod.env /app/.env

RUN yarn install

RUN yarn build

FROM httpd:2.4-alpine

COPY --from=0 /app/dist /usr/local/apache2/htdocs

RUN sed -i \
		-e 's/^#\(Include .*httpd-ssl.conf\)/\1/' \
		-e 's/^#\(LoadModule .*mod_ssl.so\)/\1/' \
		-e 's/^#\(LoadModule .*mod_socache_shmcb.so\)/\1/' \
		conf/httpd.conf

EXPOSE 443
