name: cupihorarios
services:
  database_prod:
    container_name: cupihorarios_db
    image: postgres:16
    env_file:
      - ./backend/prod.env
    ports:
      - 5433:5432
    volumes:
      - ./backend/db/backups/postgres_dump.sql:/docker-entrypoint-initdb.d/postgres_dump.sql
    profiles:
      - prod
    restart: always

  backend_dev:
    container_name: cupihorarios_back
    env_file:
      - ./backend/.env
    build:
      context: ./backend/
    ports:  
      - 8001:8000
    profiles:
      - dev

  backend_prod:
    container_name: cupihorarios_back
    env_file:
      - ./backend/prod.env
    build:
      context: ./backend/
    ports:  
      - 8001:8000
    profiles:
      - prod
    depends_on:
      - database_prod
    volumes:
      - ../certificates/server.crt:/etc/ssl/certs/server.crt:ro
      - ../certificates/server.key:/etc/ssl/certs/server.key:ro
    restart: always

  frontend_dev:
    container_name: cupihorarios_front
    env_file:
      - ./frontend/.env
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    ports:  
      - 443:443
    depends_on:
      - backend_dev
    profiles:
      - dev

  frontend_prod:
    container_name: cupihorarios_front
    env_file:
      - ./frontend/prod.env
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend/
    ports:  
      - 8081:80
      - 4444:443
    depends_on:
      - backend_prod
    profiles:
      - prod
    volumes:
      - ../certificates/server.crt:/usr/local/apache2/conf/server.crt:ro
      - ../certificates/server.key:/usr/local/apache2/conf/server.key:ro
    restart: always
